version: '3'

services:
  lapseenv:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: lapse
    security_opt:
      - seccomp:unconfined
    container_name: lapse
    ports:
      - "7776:22"
      - "7777:7777"
    volumes:
      - .:/home/lapse
    working_dir: /home/lapse
    hostname: lapse

